version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/StudentSystem02
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh